=== kowalovv/parser/src/main/resources/store.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="store" type="StoreType"/>

    <xs:complexType name="StoreType">
        <xs:sequence>
            <xs:element name="departments" type="DepartmentsType"/>
            <xs:element name="orders" type="OrdersType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DepartmentsType">
        <xs:sequence>
            <xs:element name="department" type="DepartmentType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DepartmentType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="employees" type="EmployeesType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="EmployeesType">
        <xs:sequence>
            <xs:element name="employee" type="EmployeeType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="EmployeeType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="details" type="DetailsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="DetailsType">
        <xs:sequence>
            <xs:element name="detail" type="DetailType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DetailType">
        <xs:sequence>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="phoneNumber" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="OrdersType">
        <xs:sequence>
            <xs:element name="order" type="OrderType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OrderType">
        <xs:sequence>
            <xs:element name="amount" type="xs:double"/>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="startDate" type="xs:dateTime"/>
            <xs:element name="endDate" type="xs:dateTime"/>
            <xs:element name="products" type="ProductsType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="ProductsType">
        <xs:sequence>
            <xs:element name="product" type="ProductType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ProductType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="producer" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

</xs:schema>

=== kowalovv/parser/src/main/resources/store.xml
<store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="store.xsd">
    <departments>
        <department id="1">
            <name>Sales</name>
            <employees>
                <employee id="1">
                    <firstName>Patryk</firstName>
                    <lastName>Kowalow</lastName>
                    <details>
                        <detail id="1">
                            <address>St. Siemianowicka 1, 52-007 Wroclaw</address>
                            <phoneNumber>661000222</phoneNumber>
                        </detail>
                    </details>
                </employee>

                <employee id="2">
                    <firstName>John</firstName>
                    <lastName>Wick</lastName>
                    <details>
                        <detail id="2">
                            <address>St. NewYork 3, 22-007 LA</address>
                            <phoneNumber>333222444</phoneNumber>
                        </detail>
                    </details>
                </employee>
            </employees>
        </department>
    </departments>

    <orders>
        <order id="1">
            <amount>10000</amount>
            <status>in progress</status>
            <startDate>2024-01-03T12:30:00</startDate>
            <endDate>2024-01-10T15:45:00</endDate>
            <products>
                <product id="1">
                    <name>RTX 4070TI</name>
                    <producer>nVidia</producer>
                </product>
                <product id="2">
                    <name>GTX 1660TI</name>
                    <producer>nVidia</producer>
                </product>
            </products>
        </order>
    </orders>
</store>
